# Generated by Django 6.1 on 2026-09-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_turno_turno_unico_por_medico_fecha_hora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=12, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=12, verbose_name='Estado nuevo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='citas.turno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de turno',
                'verbose_name_plural': 'Historial de turnos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
